services:
  mydrop:
    image: docker.cnb.cool/likesrt/mydrop:latest
    container_name: mydrop
    env_file:
      - ./.env
    ports:
      # 对外暴露端口（默认对任意地址开放）
      - "${PORT:-3000}:${PORT:-3000}"
      # 不对外直接暴露端口：注释上一行，取消注释下一行
      # - "127.0.0.1:${PORT:-3000}:${PORT:-3000}"
    volumes:
      # 挂载上传文件，数据库和日志到宿主机，便于持久化
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./database:/app/database
    restart: unless-stopped
    # 如需本地构建镜像（而非拉取），请改为：
    # build: .
    # image: mydrop:dev
