services:
  mydrop:
    build: .
    image: mydrop:latest
    container_name: mydrop
    env_file:
      - ./.env
    ports:
      # Simple mapping using a single variable PORT for both sides.
      # Change PORT in .env to adjust published port.
      - "${PORT:-3000}:${PORT:-3000}"
      # 禁止端口访问需要
      # - "127.0.0.1:${PORT:-3000}:${PORT:-3000}"
    volumes:
      # 挂载上传文件，数据库和日志到宿主机，便于持久化
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - ./database:/app/database
    restart: unless-stopped
